### ISSUE TITLE
sposób na przekazanie rozwiązania do testerki

### ISSUE THREAD

**Issue by phoe-krk** [gauee/RushHour#3]
Będę chciał pisać w Common Lispie, a wątpię, żeby ktokolwiek z Was chciał implementować testerkę dla tego języka.
Czy będzie opcja po prostu przekierowania STDIN/STDOUT do/z testerki?

**Comment by gauee** [comment]
Jednym z kryteriów oceny jest również, czas rozwiązania zadań. 
Prosiłbym o podanie konfiguracji środowiskowej oraz komend potrzebnych do uruchomienia rozwiązania napisanego w Lispie. Zobaczymy wtedy czy lepiej będzie zaimplementować testerkę czy dodać obsługę do pobierania przykładów testowych.

**Comment by phoe-krk** [comment]
Wymagana implementacja: SBCL. Da się uruchomić program przez "sbcl --script file.lisp".
