### ISSUE TITLE
Problem description clarifications

### ISSUE THREAD

**Issue by shybovycha** [gauee/RushHour#4]
Mam kilka pytań odnośnie zadania:

1. Czy samochód X zawsze będzie się znajdował w tej samej pozycji? Ewentualnie, czy zawsze musi osiągnąć pozycję `(3,5)`? Z treści to nie do końca jasne.
2. W przykładzie samochód **A** przesunął się tylko o dwie klatki - czy należy znaleść minimalne możliwe przesunięcia dla każdego samochodu, czy może to być dowolne przesunięcie? _(W drugim przypadku samochód **A** może zostać w klatce `(0,4)`)_
3. Co musi zostać wypisane w razie, gdy nie jest możliwe obliczenie zestawu przesunięć samochodów, który prowadzi samochód **X** do klatki `(3,5)`?

**Comment by gauee** [comment]
Ad1.
Samochód X może znajdować się w różnej pozycji i miejscu, ale zawsze w takiej umożliwiającej osiągnięcie pozycji (3,5)

Ad2.
Tak, porównywalna będzie liczba pojedynczych przesunięć, więc im mniej tym lepiej. 

Ad3.
Samochód X zawsze będzie w stanie osiągnąć pozycję (3,5)
