### ISSUE TITLE
Testy nie są poprawne

### ISSUE THREAD

**Issue by shybovycha** [gauee/RushHour#8]
Testy są błędne. To nie odpowiada formatu wejścia, opisanemu w README:

```
2
8
A 0 0 0 2
C 0 3 0 4
E 1 0 2 0
I 1 4 2 4
M 3 1 3 3
N 2 5 4 5
O 5 3 5 5
X 1 2 2 2
```

**Comment by gauee** [comment]
Akurat te testy nie są docelowymi, które prawdopodobnie nie będą publiczne.

**Comment by shybovycha** [comment]
Rozumiem to, ale obecnie nie da się przetestować programu, wysyłając go do systemu...

**Comment by gauee** [comment]
Opublikowałem przykładowy INPUT dla 4 różnych poziomów trudności
